### ISSUE TITLE
Please publish the to NPM

### ISSUE THREAD

**Issue by evgygor** [TwitchBronBron/brightscript-parser#3]
Could you please publish the latest changes?

Thanks

**Comment by TwitchBronBron** [comment]
Oops. Yes, I completely forgot after that last PR. Thanks for the reminder.

**Comment by TwitchBronBron** [comment]
Sorry for the delay. The "publish-to-npm" part of my build process was failing, I didn't have time until today to get that working. It should be in NPM now as version [1.1.0](https://www.npmjs.com/package/brightscript-parser)

**Comment by evgygor** [comment]
Thanks a lot!
