### ISSUE TITLE
How does it compare to RokuRoad/bright

### ISSUE THREAD

**Issue by tmm1** [TwitchBronBron/brightscript-parser#4]
https://github.com/RokuRoad/bright

**Comment by TwitchBronBron** [comment]
This repository is much less sophisticated than RokuRoad/bright. Looking at the commit history, I started this project before RokuRoad/bright existed. This repository was created to support [brightscript-formatter](https://github.com/TwitchBronBron/brightscript-formatter). Ideally, I would like to switch brightscript-formatter over to using a full-featured parser....but I just don't have the time right now.

**Comment by tmm1** [comment]
Thanks for the context!

It looks like https://github.com/willowtreeapps/wist also has a brightscript parser, and has a `wist-fmt` command which can prettify brightscript.

It's nice to see the community building up tooling around brightscript!
